# mysql
Get http://localhost/masterServer/index.php/api/mysql

### mysql
POST http://localhost/masterServer/index.php/api/mysql
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName


### access
Get http://localhost/masterServer/index.php/api/access

### access
POST http://localhost/masterServer/index.php/api/access
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName

.

### sql server
Get http://localhost/masterServer/index.php/api/sqlServer

### sql server
POST http://localhost/masterServer/index.php/api/sqlServer
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName



### oracle
Get http://localhost/masterServer/index.php/api/oracle


### oracle
POST http://localhost/masterServer/index.php/api/oracle
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName
