

get http://127.0.0.1:5000/mysql

###
POST http://127.0.0.1:5000/mysql
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName

# ////////////////////////////////////////////////////////////////////////////////////


###
get http://127.0.0.1:5000/access

###
POST http://127.0.0.1:5000/access
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName

# ////////////////////////////////////////////////////////////////////////////////////





###
get http://127.0.0.1:5000/sqlserver



###
POST http://127.0.0.1:5000/sqlserver
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName



# ////////////////////////////////////////////////////////////////////////////////////





###
get http://127.0.0.1:5000/oracle



###
POST http://127.0.0.1:5000/oracle
Content-Type: application/x-www-form-urlencoded

imageData=base64&imageName=fileName

